### ISSUE TITLE
Add information about how to add IntelliSense to VS Code

### ISSUE THREAD

**Issue by tstringer** [Microsoft/nodejs-guidelines#13]
IntelliSense with VS Code while programming node is absolutely crucial in ensuring a great development experience.  I can write up the quick how-to on adding IntelliSense to node application projects in VS Code.

**Comment by tstringer** [comment]
*Note: I am unable to self-assign myself to this issue (the intention)*

**Comment by mousetraps** [comment]
Is there any reason we can't just point to the VSCode docs here?

**Comment by tstringer** [comment]
Do we even explain in the VS Code docs how to work with TS definition files?  From what I see, [the IntelliSense information on VS Code docs](https://code.visualstudio.com/Docs/editor/editingevolved#_intellisense) is rather sparse and doesn't seem to explain the *how*.

**Comment by mousetraps** [comment]
How about we link to the specific section on nodejs in the docs? https://code.visualstudio.com/docs/runtimes/nodejs

**Comment by tstringer** [comment]
:+1: :white_check_mark: That's perfect!  I hadn't seen that section before.  Very descriptive and I completely agree that we should link to this section and that should suffice!

**Comment by jasonyueyang** [comment]
This [blog](http://blogs.msdn.com/b/vscode/archive/2015/06/05/mobile-hybrid-apps-with-vs-code-and-ionic.aspx), pointed out by @egamma, has some helpful description about this.
