### ISSUE TITLE
Command line pain points

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejs-guidelines#16]
> IN PROGRESS We're currently planning the next Windows release, so it's a great time to let us know your biggest command line pain points! 

I find the bash shell in Git 4 Windows and ConEmu works really well for me and removes many of the issues with cmd window resize, text selection, cut and paste, fonts, Unicode support and terminal emulation for colours. Admittedly Win 10 Cmd window is an improvement here. I don't use PowerShell, perhaps I should investigate but I'm pretty set in my ways

So far my number one pain has been installing native modules so it's great you have a section on that here. They often fail and seems to be very sensitive to both the version of VS tooling installed and it's health (repair sometimes helps). Python version can also be a problem if you have it installed for projects.

Another issue is npm assumes windows shell when running package.json scripts. This is a pain if you are using bash but is actually part of the larger issue of writing portable npm scripts. These make a fantastic light weight build facility avoiding the need for make, grunt, gulp, webpack etc. for smaller projects. But they need to be portable.across dev platforms. I nearly added these in a PR here. I investigated this issue and made [comprehensive notes](https://github.com/npm/npm/issues/9420) in a npm issue but it needs careful engineering.

Underlying this is probably the point many devs create npm packages assuming a *nix dev env and so do not address these few remaining portability pain points when using Windows..

**Comment by SteveALee** [comment]
PS another occasional pain point was updating path when node or npm did not do so correctly (even after loging out and in again). This is much better in Win 10 due to he great new Path editor in build 10586 as @shanselman  said "Lots of improvements coming in Windows 10 build 10586 but reviewers don't show the subtle new stuff WE care about: https://t.co/4JwyMzCs9y"

**Comment by SteveALee** [comment]
@mousetraps So one way to address the problem of creating portable scripts is to not do it :)

node JS can be written portable with care and it's easy to [create node CLI utilities](https://developer.atlassian.com/blog/2015/11/scripting-with-node/?utm_source=nodeweekly&utm_medium=email) and run them from the scripts section.

This is a little more complex but doesn't involve all the complexity / learning curve of grunt/gulp etc. or need to install a make on windows.

Still my prefered solution would be a proper POSIX shell on Windows out of the box :)

**Comment by mjbvz** [comment]
Closing since this has been inactive for a while and the issue is pretty open ended.

Please let me know if you want to reopen this issue and continue working here. This certainly sounds like pain point that could use more attention in these guidelines.

Thanks.
