### ISSUE TITLE
Add Test Driven Development Section

### ISSUE THREAD

**Issue by erikschlegel** [Microsoft/nodejs-guidelines#19]
This should include leveraging tools like PhantomJS, Sinon, Chai and Karma as part of Azure CI builds. I'll include some sample repo's with workable examples that folks can clone and spin up.

**Comment by mousetraps** [comment]
Totally. How about we have a section on testing your app, and another section on CI builds, which would include anything specific to CI?

**Comment by tstringer** [comment]
:+1: to @mousetraps on the comment.  That division and distinct sections would be great.

**Comment by dakebl** [comment]
Hello everyone, I hope you don't mind me attempting a first pass at this request.
I've raised PR #77 as a first attempt and would welcome some feedback before continuing.

**Immediate Considerations**
It's probably worth adding a brief definition of TDD, and It would be good to highlight any azure/node specific gotcha's and considerations around js asynchrony too.

I have little experience Azure CI, so I'll leave those considerations to someone else 😄

**Comment by mjbvz** [comment]
Closing as out of scope
