### ISSUE TITLE
Add styleguides

### ISSUE THREAD

**Issue by MarkTiedemann** [Microsoft/nodejs-guidelines#29]
[At some point, everyone should probably read a styleguide.](https://xkcd.com/1513/)

How about adding some of the most popular ones?

- [airbnb](https://github.com/airbnb/javascript)
- [idiomatic](https://github.com/rwaldron/idiomatic.js/)
- [google](http://google.github.io/styleguide/javascriptguide.xml)

**Comment by romuloctba** [comment]
I'm not sure if styleguides should come up at a beginners handbook, but they are usefull for sure. I just think they are somehow better aimed to people who are already familiar with Node

**Comment by romuloctba** [comment]
But yeah, they do fit into 'guidelines', since they are a guide.... hm... I'll wait for more opinions, since mine is not solid enough :P

**Comment by mousetraps** [comment]
One interesting thing about JS is that there is no single styleguide, and people find their style in many different ways. Styleguides are one of them, but I've also seen a more dynamic "follow influencers in the community, and learn from them." 

So it would be awesome to have a section on this, but let's preface it with something like that - effectively make it clear that there is no One styleguide, but also don't leave people feeling totally overwhelmed trying to pick the Best one.

Including a section on tools to help enforce this style would also be useful.

**Comment by mjbvz** [comment]
Closing since this has been inactive for a while. Feel free to submit a PR or let me know if you are still interested in working here and we can reopen the issue for further discussion.

Thanks.
