### ISSUE TITLE
Complete available editors / IDEs section

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/nodejs-guidelines#3]

**Comment by choopage** [comment]
@mousetraps I enjoy using WebStorm. What do you think of this write-up for WebStorm?

**WebStorm** is a lightweight yet powerful IDE, perfectly equipped for complex client-side development and server-side development with Node.js. It supports TypeScript 1.6, Flow, ES6, Angular 2, TSLint, npm scripts, and more. For more information, check out [jetbrains.com/webstorm](http://jetbrains.com/webstorm).
