### ISSUE TITLE
Add a "Using Next Generation Node.js"  section

### ISSUE THREAD

**Issue by MarkTiedemann** [Microsoft/nodejs-guidelines#30]
This section should include:

- a quick showcase of new ES6/ES2015 and experimental ES7 features
- a tutorial for transpiling with [babel](https://github.com/babel/babel/)

**Comment by romuloctba** [comment]
:clap: :clap: :clap:
will you pr? or this is just an (great) idea?

**Comment by SteveALee** [comment]
There are other transpilers, but babel has become the "goto". Make sure to cover babel 6 and need for the ES2015 Preset.

**Comment by MarkTiedemann** [comment]
Started working on it, will PR soon.

The Babel part is almost done. See: [https://gist.github.com/MarkTiedemann/69bb6d7a7930074943f3](https://gist.github.com/MarkTiedemann/69bb6d7a7930074943f3)

Going to start working on the ES6 and ES7 features soon. I'm thinking I should only include the most popular ones.

Any must-haves? :)

**Comment by mousetraps** [comment]
Sweet! We should also add some content for TypeScript + Node.js, but we should be able to find someone else to write that if you don't have and/or want to learn that :stuck_out_tongue_winking_eye:

**Comment by mousetraps** [comment]
@noelabrahams as one of the most active TS + Node.js folks I know... any chance you might be interested in contributing some TypeScript + Node.js content? :smiley:

**Comment by mousetraps** [comment]
Also, I think it would be great to link to https://github.com/lukehoban/es6features

cc @lukehoban

**Comment by NoelAbrahams** [comment]
@mousetraps, I'm happy to contribute a few bits, although it might be next week.

**Comment by SteveALee** [comment]
Also https://nodejs.org/en/docs/es6/ kinda tracks which ES6 features are in which version of nodejs

**Comment by mjbvz** [comment]
Closing since this has been inactive for a while and the next generation is now the current generation :)

Feel free to submit a PR or let me know if you are still interested in working on this and we can reopen the issue for further discussion. Based on the comments, I did add a link to the es6 features resource.

Thanks.
