### ISSUE TITLE
Should we cover node as build tool for browser apps?

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejs-guidelines#31]
This may be out of scope but is part of a full stack development capability.

A very common use case of node is acting as a build platform for browsers. Many build tools run in node: grunt, gulp, webpack, though others do not: npm scripts, make.
1. dependency tracking and re build
2. hot loading and browsersync
3. integration with CI and CD tooling - though often done via git hooks

Other node tools provide key functionality such as 
1. Transpiling ES6 to ES5 including source maps for browser dev tools
2. Preparing assets - catenation, uglification, gzipping
3. Providing Cross platform CommonJS modules - though this is managed through NPM

**Comment by mousetraps** [comment]
Sure, this info would be useful. Thoughts on a good place for it? (new or existing). Keep in mind that we're trying to keep top-level sections as broad as possible at the moment to give them a chance to evolve without refactorings, though not so broad such that they overlap *too* much.

**Comment by SteveALee** [comment]
If you want broad then how about  a "build and test section" including TDD as suggested in #19? Perhaps call it "Developer workflows"? That may or may not including "Deployment" depending on if you subscribe to the DevOps buzz word or not :)

**Comment by mjbvz** [comment]
Closing as out of scope
