### ISSUE TITLE
Could add  Visual Studio Dev Essentials program 

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/nodejs-guidelines#34]
Could add the [Visual Studio Dev Essentials program]( https://www.visualstudio.com/products/visual-studio-dev-essentials-vs) to list of node related Microsoft services on home page.

Mind you, as far as I can see this is mostly a compilation of existing free stuff (and MSDN subscriptions could be a better deal).

Thoughts?

**Comment by mousetraps** [comment]
Great idea - let's add it to the msft offerings section!
