### ISSUE TITLE
Add section dedicated to Node.js in Azure

### ISSUE THREAD

**Issue by tstringer** [Microsoft/nodejs-guidelines#39]
Our offerings for Node.js in Azure are vast, and we should have a dedicated section for working with Node.js in Azure, and cloud-specific actions and knowledge.  Thoughts?

**Comment by mousetraps** [comment]
Yeah, that would be awesome!

Also as a general note... I expect this repo to continue evolving, and we don't really know what it's going to morph into, so let's get the content together, and then we can figure out where it should live. Worst case scenario we post it somewhere else and link to it :smiley:

**Comment by tstringer** [comment]
@mousetraps Pull Request #41 created for this. Already working on additions to this Azure section! :+1:

**Comment by SteveALee** [comment]
Do we feel Windows Server is a viable platform too or should we focus on cloud / azure?

In either case the [Deploying node on Linux](https://certsimple.com/blog/deploy-node-on-linux?utm_source=nodeweekly&utm_medium=email) strikes me as a good model to follow.

**Comment by tstringer** [comment]
@SteveALee Not a bad idea to have a section on Windows Server, but I think Azure should have its own dedicated session.
